version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
     - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: intraway
      MONGO_INITDB_ROOT_PASSWORD: iwjaja